# Generated by Django 5.2.6 on 2025-11-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='quiz_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
